# Generated by Django 4.1.3 on 2023-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_book_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
