# Generated by Django 4.1.3 on 2023-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_book_isbn_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
